apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-crud-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-crud
  template:
    metadata:
      labels:
        app: flask-crud
    spec:
      containers:
      - name: flask-crud-container
        image: docker.io/salamanteri/flask-crud:latest
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: flask-crud-service
spec:
  type: LoadBalancer
  selector:
    app: flask-crud
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
